* Description
Show authenticated users, on the map, where the weathers stations (WS) are, by displaying weather station icons, and their when clicked, zoom to them, and show the following WS-info, from this site (https://api.weather.gov/), in the info popup:

- WS Name / ID
- Forecast datetime
- Latest forecast for selected value or all:
- Air temperature (F)
- Humidity
- Dew Point
- Wind speed
- Wind direction
- Gust
- Air quality

* TODOs
** DOING Get WS-geo-info

The WS geometry information has this description:
#+begin_quote
A GeoJSON geometry object. Please refer to IETF RFC 7946 for information on the GeoJSON format.
#+end_quote

So can we use the data in a GeoJSON geometry object?

** DOING Get camera-geo-info

the `get-cameras` function says

"Builds a GeoJSON response of the current wildfire cameras."

So chances are good we can!

** DOING See if WS-geo-info looks like it translated into the same format as camera-geo-info
** TODO Gather other WS-info url calls.
** TODO confirm ws-geo-info to camera-geo-info
** TODO confirm WS-info calls
** TODO Get WS-icon
** TODO Use WS-geo-info the same way camera-geo-info is to create a map.
** TODO Display WS-info when clicked.
** TODO Zoom to WS-icon when clicked
