* notes

** og

setup build uberjar command

- compile js into jar
- compile java into jar
- include sql
- add meta data
-

so triangulum provides, which i don't think will be available

#+begin_src sh
clojure -X triangulum.packaging/build-uberjar :app-name $ARTIFACT_ID :main-ns $MAIN_NAMESPACE
#+end_src

- TODO what are we calling the app e.g pyregence?
- TODO does the main-ns args get a quote? or is it a string?
- TODO will we have to expose that triangulum alias in deps? no we can call -X, but we likely will want to pass args... where? In jenkins? yeah the args will be in jenkins.
- TOOD were using -X to build the uberjar, why -T is whats used in the docs.

So our main namespace needs to...

;; is here something wrong with this org babel tangle? It comes out different in the file then whats below
#+begin_src clojure :tangle src/clj/pyregence/main.clj
(ns pyregence.main
  (:gen-class))

;; TODO needs to be able to expose two funtions updating the db and starting the server
(defn -main [& args]
  ;; TODO should it be able to choose between start server and update here?  1
  ;; TODO start server
  ;; TODO udpate db
  (println args))
#+end_src


ok so for the moment i'm going to ditch the triangulum stuff as its getting in the way, we can pick it up later



and we need to call `npm install` & -M:compile-cljs and then

** try building our own build.clj

#+begin_src shell
  clj -T:build uber
#+end_src

** build uberjar function

*** old

according to dev docs we just call run-server, below, todo double check that... especially bc that doesn't exist.

**** cljs

:compile-cljs     {:main-opts ["-m" "pyregence.compile-cljs" "compile-prod.cljs.edn"]}

**** clj

:production       {:jvm-opts ["-XX:MaxRAMPercentage=90" "-XX:+PrintFlagsFinal"]}


*** new
args


#+begin_src clojure
  ;; sig
  {:keys [app-name main-ns src-dirs resource-dirs bindings compile-opts java-opts manifest]
   :or   {src-dirs      ["src"]
          resource-dirs ["resources"]
          bindings      {}
          compile-opts  {}
          java-opts     []
          manifest      {}}
   :as   params}

  {:app-name  "Pyregence"
   ;; TODO is this right? how where is the command that actually starts it wv
   ;; TODO should the main ns be a string?
   :main-ns   "pyregence.main"
   :java-opts ["-XX:MaxRAMPercentage=90" "-XX:+PrintFlagsFinal"]}

#+end_src

#+begin_src clojure
    (defn build-uberjar
    "Create an UberJAR suitable for deployment and use as an application."
    [{:keys [app-name main-ns src-dirs resource-dirs bindings compile-opts java-opts manifest]
      :or   {src-dirs      ["src"]
             resource-dirs ["resources"]
             bindings      {}
             compile-opts  {}
             java-opts     []
             manifest      {}}
      :as    params}]

    ;; Validate input args
    (assert-required "build-uberjar"
                     params
                     [:app-name :main-ns])

    (assert-specs "build-uberjar"
                  params
                  :app-name      ::app-name
                  :main-ns       ::main-ns
                  :src-dirs      ::src-dirs
                  :resource-dirs ::resource-dirs
                  :bindings      ::bindings
                  :compile-opts  ::compile-opts
                  :java-opts     ::java-opts
                  :manifest      ::manifest)

    (let [version           (get-calendar-commit-version)
          uberjar-file-name (get-uberjar-file-name app-name version)]

      ;; Delete the jar-content folder
      (b/delete {:path jar-content})

      ;; Copy static files to jar-content folder
      (b/copy-dir {:src-dirs   (concat src-dirs resource-dirs)
                   :target-dir jar-content})

      ;; Compile Clojure source code to classes in the jar-content folder
      (b/compile-clj {:src-dirs     src-dirs
                      :class-dir    jar-content
                      :basis        basis
                      :bindings     bindings
                      :compile-opts compile-opts
                      :java-opts    java-opts})

      ;; Package jar-content into an UberJAR file
      (b/uber {:class-dir jar-content
               :uber-file uberjar-file-name
               :basis     basis
               :main      main-ns
               :manifest  manifest})

      (println (format "UberJAR file created: \"%s\"" uberjar-file-name))))
#+end_src

**

#+RESULTS:

Downloading: djblue/portal/maven-metadata.xml from clojars
Downloading: org/clojure/clojure/maven-metadata.xml from central
Execution error (FileNotFoundException) at clojure.tools.build.tasks.write-pom/eval4198$loading (write_pom.clj:9).
Could not locate clojure/data/xml/tree__init.class, clojure/data/xml/tree.clj or clojure/data/xml/tree.cljc on classpath.

Full report at:
/tmp/clojure-18070644554388781669.edn
[ Babel evaluation exited with code 1 ]



** other

invoke jar

java -jar and args


when build triangulum has a place to specific main class

should have commands.

- update database
- m build db, migrate command (apply changes),
- start server


- build db then start server. k
-

* meeting notes

TODO uberjar stores compiled javascript
uberjar multiple purpose entry
- start server
- update database (what would those commands be)

goal is to decrease packages

setup on jenkins, setup a release pipeline so that jenkins builds and executes.

triangulum package namespace expose via an alias in pyregence and call it.

build-uberjar

- compile js into jar
- compile java into jar
- include sql
- add meta data
-

* current dev docs on deployment

# Pyregence server deployment instructions
```
ssh -A [user]@pyregence.org
# pass domain password
cd /sig/pyregence
git pull
clojure -M:compile-cljs
# if you have server side changes
kill XXXX
(DEV-SERVER) nohup clojure -M:run-server -p 9002 -P 8002 -o logs >/dev/null 2>&1 &
(PROD-SERVER) nohup clojure -M:run-server -P 8443 -o logs >/dev/null 2>&1 &
```

What server? Does it matter? i think not

* deployment notes from oliver

its on inyo under /home/sig-app/pyregence

* github readme says:

clojure -M:build-db functions
clojure -M:default-ssl-opts:server start -m [dev|prod] [-p 8080] [-P 8443] [-r/--repl]

* oliver says

its just bb deploy


#+begin_src clojure
  {:tasks
 {:enter       (println (str (java.util.Date.)
                             " task " "'" (:name (current-task)) "'"
                             " running... "))
  :leave       (println (str (java.util.Date.)
                             " task " "'" (:name (current-task)) "'"
                             " done."))
  -project     "cljweb-pyregence"
  reload       (shell "systemctl --user daemon-reload")
  status       {:depends [-project]
                :task    (shell (format "systemctl --user status %s" -project))}
  start        {:depends [-project]
                :task    (shell (format "systemctl --user start %s" -project))}
  stop         {:depends [-project]
                :task    (shell (format "systemctl --user stop %s" -project))}
  restart      (do
                 (run 'stop)
                 (run 'start))
  compile      (clojure "-M:compile-cljs")
  pull         (shell "git pull")
  migrate      (clojure "-M:build-db migrate")
  build-all    (clojure "-M:build-db build-all")
  dev-data     (clojure "-M:build-db build-all --dev-data")
  functions    (clojure "-M:build-db functions")
  prod         (do
                 (run 'install)
                 (run 'functions)
                 (run 'clean)
                 (run 'compile)
                 (run 'server-start))
  dev          (do
                 (run 'install)
                 (run 'functions)
                 (clojure "-M:default-ssl-opts:figwheel"))
  dev-norepl    (do
                  (run 'install)
                  (run 'functions)
                  (shell "clojure -M:default-ssl-opts:figwheel-lib -m figwheel.main -b \"compile-dev\""))
  install      (shell "npm install")
  deploy       (do
                 (run 'stop)
                 (run 'pull)
                 (run 'install)
                 (run 'clean)
                 (run 'compile)
                 #_(run 'migrate)
                 (run 'functions)
                 (run 'start))
  clean        (shell "rm -rf target")
  server-start (clojure "-M:server start")}}

#+end_src

**** command breakdown

- npm install
- -M:compile-cljs
- -M:build-db functions
- -M:server start
- call system d


**** system d


                  cljweb-pyregence.service - A service to launch a server written in clojure
     Loaded: loaded (/home/sig-app/.config/systemd/user/cljweb-pyregence.service; enabled; preset: enabled)
     Active: active (running) since Mon 2025-03-17 18:05:54 UTC; 3 days ago
   Main PID: 3638817 (java)
      Tasks: 46 (limit: 38300)
     Memory: 917.4M (peak: 1.7G)
        CPU: 1h 10min 35.023s
     CGroup: /user.slice/user-1004801267.slice/user@1004801267.service/app.slice/cljweb-pyregence.service
             └─3638817 /usr/bin/java -Djavax.net.ssl.keyStore=resources/runway.pkcs12 -Djavax.net.ssl.keyStorePassword=RomeoUniformNovemberWhiskeyAlfaYankee -Dclojure.basis=.cpcache/333989438.basis -classpath src/clj:src/cljs:resources:target:/home/sig-app/.m2/reposito>
~
~
~

 think we have to let go of Babashka.


** uberjar docs


When preparing an application, it is common to compile the full app + libs and assemble the entire thing as a single uberjar.

It is important that your main Clojure namespace should have =(:gen-class)=, for example:

#+BEGIN_EXAMPLE clojure
   (ns my.lib.main
    ;; any :require and/or :import clauses
    (:gen-class))
#+END_EXAMPLE

And that namespace should have a function like:

#+BEGIN_EXAMPLE clojure
   (defn -main [& args]
    (do-stuff))
#+END_EXAMPLE

An example build for a compiled uberjar will look like this:

#+BEGIN_EXAMPLE clojure
   (ns build
    (:require [clojure.tools.build.api :as b]))

  (def lib 'my/lib1)
  (def version (format "1.2.%s" (b/git-count-revs nil)))
  (def class-dir "target/classes")
  (def uber-file (format "target/%s-%s-standalone.jar" (name lib) version))

  ;; delay to defer side effects (artifact downloads)
  (def basis (delay (b/create-basis {:project "deps.edn"})))

  (defn clean [_]
    (b/delete {:path "target"}))

  (defn uber [_]
    (clean nil)
    (b/copy-dir {:src-dirs ["src" "resources"]
                 :target-dir class-dir})
    (b/compile-clj {:basis @basis
                    :ns-compile '[my.lib.main]
                    :class-dir class-dir})
    (b/uber {:class-dir class-dir
             :uber-file uber-file
             :basis @basis
             :main 'my.lib.main}))
#+END_EXAMPLE

This example directs =compile-clj= to compile the main namespace (by default source will be loaded from the basis :paths). Compilation is transitive and all namespaces loaded by the compiled namespace will also be compiled. You may need to add additional namespaces if code is dynamically or optionally loaded.

The deps.edn and build execution will look the same as the prior example.

You can create the uber jar build with:

#+BEGIN_EXAMPLE clojure
   clj -T:build uber
#+END_EXAMPLE

The output of this build will be an uberjar at =target/lib1-1.2.100-standalone.jar=. That jar contains both a compiled version of this project and all of its dependencies. The uberjar will have a manifest referring to the =my.lib.main= namespace (which should have a =-main= method) and can be invoked like this:

#+BEGIN_EXAMPLE
   java -jar target/lib1-1.2.100-standalone.jar
#+END_EXAMPLE

**** [[#_parameterized_builds][]]Parameterized builds


In the builds above we did not parameterize any aspect of the build, just chose which functions to call. You may find that it's useful to parameterize your builds to differentiate dev/qa/prod, or version, or some other factor. To account for function chaining at the command line, it is advisable to establish the common set of parameters to use across your build functions and have each function pass the parameters along.

For example, consider a parameterization that includes an extra set of dev resources to set a local developer environment. We'll use a simple =:env :dev= kv pair to indicate this:

#+BEGIN_EXAMPLE clojure
   (ns build
    (:require [clojure.tools.build.api :as b]))

  (def lib 'my/lib1)
  (def version (format "1.2.%s" (b/git-count-revs nil)))
  (def class-dir "target/classes")
  (def jar-file (format "target/%s-%s.jar" (name lib) version))
  (def copy-srcs ["src" "resources"])

  ;; delay to defer side effects (artifact downloads)
  (def basis (delay (b/create-basis {:project "deps.edn"})))

  (defn clean [params]
    (b/delete {:path "target"})
    params)

  (defn jar [{:keys [env] :as params}]
    (let [srcs (if (= env :dev) (cons "dev-resources" copy-srcs) copy-srcs)]
      (b/write-pom {:class-dir class-dir
                    :lib lib
                    :version version
                    :basis @basis
                    :src-dirs ["src"]})
      (b/copy-dir {:src-dirs srcs
                   :target-dir class-dir})
      (b/jar {:class-dir class-dir
              :jar-file jar-file})
      params))
#+END_EXAMPLE

The other aspects of deps.edn and invocation remain the same.

Invocation that activates :dev environment will look like this:

#+BEGIN_EXAMPLE
   clj -T:build jar :env :dev
#+END_EXAMPLE

The kv params are passed to the =jar= function.
