/**********************************************************************
 * Extern for introJs
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var introJs = {
  "fn": {
    "addHints": function () {},
    "addStep": function () {},
    "addSteps": function () {},
    "clone": function () {},
    "currentStep": function () {},
    "exit": function () {},
    "goToStep": function () {},
    "goToStepNumber": function () {},
    "hideHint": function () {},
    "hideHints": function () {},
    "nextStep": function () {},
    "onafterchange": function () {},
    "onbeforechange": function () {},
    "onbeforeexit": function () {},
    "onchange": function () {},
    "oncomplete": function () {},
    "onexit": function () {},
    "onhintclick": function () {},
    "onhintclose": function () {},
    "onhintsadded": function () {},
    "onskip": function () {},
    "previousStep": function () {},
    "refresh": function () {},
    "removeHint": function () {},
    "removeHints": function () {},
    "setOption": function () {},
    "setOptions": function () {},
    "showHint": function () {},
    "showHintDialog": function () {},
    "showHints": function () {},
    "start": function () {}
  },
  "instances": {},
  "version": {}
};
/**********************************************************************
 * End Generated Extern for introJs
/**********************************************************************/
