var ol;
ol.Map;
ol.Map.addOverlay;
ol.Map.getView;
ol.Map.getOverlayById;
ol.Map.on;
ol.Map.getLayers.getArray;
ol.View;
ol.View.fit;
ol.View.getZoom;
ol.View.getMaxZoom;
ol.View.getMinZoom;
ol.View.setZoom;
ol.View.getResolution;
ol.View.getProjection.getCode;
ol.Overlay;
ol.Overlay.setPosition;
ol.control;
ol.control.defaults;
ol.proj;
ol.proj.fromLonLat;
ol.layer;
ol.layer.getSource;
ol.layer.setOpacity;
ol.layer.Tile;
ol.source;
ol.source.updateParams;
ol.source.OSM;
ol.source.TileWMS;
ol.format.WMSCapabilities;

// Specific to implementation using evt as symbol for returned event.
var evt;
evt.coordinate;
