* Configuring A GeoServer for Pyregence

** Installation Requirements

TODO FILL IN

** Configuration

*** Allowing Cross-Origin Resource Sharing (CORS)

Open [GeoServer location]/webapps/GeoServer/WEB-INF/web.xml for editing.
Uncomment the following 2 blocks:

#+begin_src sh
<!-- Uncomment following filter to enable CORS -->
<filter>
  <filter-name>cross-origin</filter-name>
#+end_src

#+begin_src sh
<!-- Uncomment following filter to enable CORS -->
<filter-mapping>
   <filter-name>cross-origin</filter-name>
#+end_src

In the first block listed above, restrict the cross origin domain by
editing the allowedOrigins param.

#+begin_src sh
<init-param>
    <param-name>allowedOrigins</param-name>
    <param-value>*pyregence.org*</param-value>
</init-param>
#+end_src

*** Enable SSL/HTTPS

The GeoServer v2.16 seems to have mismatched versions of the required https and
ssl files. To correct this, download the Jetty distribution file. This example uses:
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.2.13.v20150730/
Copy the following files from the archive to the coresponding GeoServer directory

- $GEOSERVER_HOME/modules/ssl.mod
- $GEOSERVER_HOME/etc/jetty-https.xml
- $GEOSERVER_HOME/etc/jetty-ssl.xml

Edit ssl.mod and jetty-ssl.xml to use the correct values for keystore location and
password.

Edit jetty-https.xml, jetty-ssl.xml, and jetty.xml to update https port.

Add the following to $GEOSERVER_HOME/start.ini
#+begin_src sh
--module=ssh
--module=https
#+end_src
