name: babashka tests

on:
  pull_request:
    branches:
      - main

jobs:
  bb-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: latest
        bb: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
        restore-keys: cljdeps-
    - run: bb test
